all: ros-build-debug-launch-utils.tex
	pdflatex ros-build-debug-launch-utils.tex
	pdflatex ros-build-debug-launch-utils.tex
	
clean:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz
	
cleanall:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz ros-build-debug-launch-utils.pdf
