all: arra-ros-rviz.tex
	pdflatex arra-ros-rviz.tex
	pdflatex arra-ros-rviz.tex
	
clean:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz
	
cleanall:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz arra-ros-rviz.pdf
