all:
	(cd ros-basics; make all)
	(cd ros-build-system; make all)
	(cd ros-tools-roslaunch; make all)
	(cd ros-tools-rqt; make all)
	(cd ros-tools-rviz; make all)
	(cd ros-topic-message-service; make all)

clean:
	(cd ros-basics; make clean)
	(cd ros-build-system; make clean)
	(cd ros-tools-roslaunch; make clean)
	(cd ros-tools-rqt; make clean)
	(cd ros-tools-rviz; make clean)
	(cd ros-topic-message-service; make clean)

cleanall:
	(cd ros-basics; make cleanall)
	(cd ros-build-system; make cleanall)
	(cd ros-tools-roslaunch; make cleanall)
	(cd ros-tools-rqt; make cleanall)
	(cd ros-tools-rviz; make cleanall)
	(cd ros-topic-message-service; make cleanall)
